In [2]:
import pandas as pd
import numpy as np

In [3]:
#Q3 panads version
pd.__version__

'3.0.6'

In [4]:
df =pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv")
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0


In [5]:
#Q2 Records count
counts = len(df)
print(f"Number of Records in the dataset: {counts}")

Number of Records in the dataset: 10000


In [6]:
#Q3 Fuel types
Fuel = df['fuel_type'].nunique()
print(f"Fuel types in the dataset: {Fuel}")

Fuel types in the dataset: 3


In [7]:
#Q4 Missing values
df.isna().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [8]:
#Q5 Max fuel efficiency
asian_cars = df[df['origin'] == 'Asia']
Max_fuel_efficiency = asian_cars['fuel_efficiency_mpg'].max()
print(f"Max fuel efficiency of Asian cars: {Max_fuel_efficiency}")

Max fuel efficiency of Asian cars: 41.2


In [9]:
#Q6 Median value of horsepower
horse_power = df['horsepower'].median()
print(f"Median value of horsepower: {horse_power}")

most_frequent = df['horsepower'].mode()[0]
print(f"Most frequent value of horsepower: {most_frequent}")

df_filled = df['horsepower'].fillna(most_frequent)

filled_horse_power = df_filled.median()
print(f"Median value of horsepower after filling missing values: {filled_horse_power}")



Median value of horsepower: 254.0
Most frequent value of horsepower: 252.0
Median value of horsepower after filling missing values: 252.0


In [31]:
#Q7 Sum of weights

#1.Select all the cars from Asia
asian_cars = df[df['origin'] == 'Asia']
#2.Select only columns vehicle_weight and model_year
df_sub = asian_cars[['vehicle_weight', 'model_year']]
#3 Select the first 7 values
df_first_7 = df_sub.head(7)
#4 Get the underlying NumPy array. Let's call it X.
X = df_first_7.to_numpy()
print(f"Underlying NumPy array (X):\n{X}\n")
#5 Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
XTX = X.T @ X
print(f"X transpose multiplied by X (XTX):\n{XTX}\n")
#6 invert XTX
XTX_inv = np.linalg.inv(XTX)
print(f"inverse of XTX (XTX_inv):\n{XTX_inv}")
#7 Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
y=np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
print(f"Array y:\n{y}\n\n")
#8 Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
w_temp = XTX_inv @ X.T
w = w_temp @ y
print(f"Weights (w):\n{w}")

total_sum = w.sum()
print(f"Sum of weights: {total_sum}")


Underlying NumPy array (X):
[[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]

X transpose multiplied by X (XTX):
[[131950500  60750580]
 [ 60750580  28041424]]

inverse of XTX (XTX_inv):
[[ 2.96830537e-06 -6.43071025e-06]
 [-6.43071025e-06  1.39675281e-05]]
Array y:
[1100 1300  800  900 1000 1100 1200]


Weights (w):
[0.13644777 0.2327492 ]
Sum of weights: 0.36919696904925486
